### ISSUE TITLE
Block Transforms Don't Honor `isDefault` Block Variations

### ISSUE THREAD

**Issue by mrwweb** [samikeijonen/uuups#34]
To reproduce:

1. Create a Block Variation with `isDefault` set to `true`. (Example below sets Media & Text block to use "Crop image to fill entire column" option by default)
2. Insert a block and the variation is used correctly
3. Insert a block that can be transformed to the block variation (e.g. Image)
4. Transform block in Step 3 to the block variation made in Step 1 (e.g. Transform Image block to Media & Text block)

Expected Outcome: The block variation with `isDefault` should be used when a block is transformed to its type.

Outcome: Transforming to a block ignores a custom default style variation and uses core options (e.g. no image fill setting).

------------

Example Code:
```js
wp.blocks.registerBlockVariation(
	'core/media-text',
	{
		isDefault: true,
		attributes: {
			imageFill: true,
		},
	}
);
```

**Comment by samikeijonen** [comment]
Interesting! 

My first reaction was that does theme have style variations for text-media or image which could mess up block transforms.

But that doesn't seem to be the case.

I assume this issue doesn't happen in other themes?

**Comment by mrwweb** [comment]
@samikeijonen Hey Sami! I have a ridiculously embarrassing admission. I filed this ticket on the completely wrong Github repo (it was meant for Gutenberg) and I have absolutely no idea how I did that. Sorry if I cause you any concerns or bewilderment. I'm shocked this even made half-sense 🤣

Closing. Thanks for all the work you do on WP!

**Comment by mrwweb** [comment]
Link to real issue: https://github.com/WordPress/gutenberg/issues/28119

**Comment by samikeijonen** [comment]
No worries!
