### ISSUE TITLE
phpcs.xml feedback

### ISSUE THREAD

**Issue by GaryJones** [samikeijonen/uuups#7]
As mentioned at https://github.com/justintadlock/mythic/issues/7#issuecomment-415202950, here are some suggestions for the PHPCS config file for this uuups repo. I've tried _not_ to comment on the clearly-opinionated preferences.

For reference, here's the [PHPCS config file](https://github.com/GaryJones/plugin-boilerplate/blob/master/.phpcs.xml.dist) for my _plugin_ boilerplate. Here's my [`composer.json`](https://github.com/GaryJones/plugin-boilerplate/blob/master/composer.json) file.

1. Rename the file to `.phpcs.xml.dist`, and add `phpcs.xml` and `.phpcs.xml` to the `.gitignore` file. This allows the distributed config file to be trumped by a local config file. Your PHP version requirement is new enough to allow the [right version of PHPCS](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.1.0) to be installed that supports this. Also see [PHPCS 3.1.1](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.1.1) which amended the preferred order.
2. Instead of [manually setting an exact path](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml) (that may not be correct for others who have a Composer configuration that doesn't use the default `vendor` path) for the `installed_paths` in the PHPCS config file, add the [PHP_CodeSniffer Standards Composer Installer Plugin
](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) to your `require-dev` dependencies. This is [suggested](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/0b38e78301729e060eed91ed83e4c3d940e877c1/composer.json#L21) by WPCS. That will handle the automatic setting of `installed_paths` on `composer update` and `composer install`. A [custom Composer script](https://github.com/GaryJones/plugin-boilerplate/blob/7957db6a07dc95a22271563d001c828dcd68c634/composer.json#L56-L58) can also be added if you want it to become standalone. 
3. Until now, I've also been putting the `p` (progress) flag in there, though there is a point of consideration that some bash scripts may need to run without any output (unless there's a violation). Instead, it may be better to leave [this](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L24) out, and locally set PHPCS to [show progress by default](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#showing-progress-by-default). Optionally, the build scripts could also use the [quieting output](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#quieting-output) option.
4. Instead of [using](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L49) the `WordPress` ruleset (which includes ALL of the sniff files, including three that are of lower quality not yet included in `WordPress-Core` or `WordPress-Extra`), it would be better to [explicitly use](https://github.com/GaryJones/plugin-boilerplate/blob/7957db6a07dc95a22271563d001c828dcd68c634/.phpcs.xml.dist#L31-L32) the `WordPress-Extra` (which includes `WordPress-Core`) and `WordPress-Docs` rulesets.
5. Lines 39 and 53, 79-86, 96, 100, 104, 110 have spaces as indentation. Your [`composer.json`](https://github.com/samikeijonen/uuups/blob/master/composer.json) has some as well on lines 3, 15-18.
6. Your [`.editorconfig`](https://github.com/samikeijonen/uuups/blob/master/.editorconfig) doesn't match [WordPress core](https://core.trac.wordpress.org/browser/trunk/.editorconfig) - JSON (and XML) files should use tabs for indentation, since NPM and Composer can now handle them when updating the config files themselves. You can also remove the [`wp-config-sample.php` reference](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/.editorconfig#L19), since your theme doesn't include that.
7. You can switch to the new format for `type="array"` properties. See [PHPCS 3.3.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0) (or my config file) for details. Don't forget to update the [comment](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L64) on line 64.
8. Line 51, 54, and 114 have `[space]/>` for the closing of elements, which is un-needed in an XML environment. If you lint this file with [Xmllint](http://xmlsoft.org/xmllint.html) (like [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/0b38e78301729e060eed91ed83e4c3d940e877c1/.travis.yml#L112-L122) and [VIPCS](https://github.com/Automattic/VIP-Coding-Standards/blob/2672675106afb5b85f9d338aa2c7a57f8dc0222d/.travis.yml#L85-L94) do with Travis, it will complain about them.
9. Switch out the `wimg/php-compatibility` ruleset (which is now https://github.com/PHPCompatibility/PHPCompatibility anyway), and `require` the `phpcompatibility/phpcompatibility-wp` package instead. You can then use the rule `PHPCompatibilityWP` instead of [`PHPCompatibility`](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L125), and get rid of all of the [excludes](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L126-L145) and [`mysql_to_rfc3339` reference](https://github.com/samikeijonen/uuups/blob/9afa702861ec099291cc51a1099306992fb31aba/phpcs.xml#L148-L153). PHPCompatibilityWP is a wrapper for PHPCompatibility which [handles](https://github.com/PHPCompatibility/PHPCompatibilityWP/blob/b26c84df3ec1d4850d0f22264a4a16482a171996/PHPCompatibilityWP/ruleset.xml#L15-L52) all of that already.
10. The `testVersion` can be changed from `5.6-99.0` to just `5.6-` (no upper limit).

**Comment by samikeijonen** [comment]
Thanks @GaryJones! I'll take a look at this later on this week, or latest next week.

**Comment by GaryJones** [comment]
I can see you use the [Theme Claim](https://github.com/m-e-h/theme-claim) package. A couple of considerations then:

> 1. Rename the file to `.phpcs.xml.dist`, and add `phpcs.xml` and `.phpcs.xml` to the `.gitignore` file. This allows the distributed config file to be trumped by a local config file. Your PHP version requirement is new enough to allow the right version of PHPCS to be installed that supports this. Also see PHPCS 3.1.1 which amended the preferred order.

Theme Claim does not yet support anything other than `phpcs.xml`, though it should be a simple fix. I've opened https://github.com/m-e-h/theme-claim/issues/2.



> 7. You can switch to the new format for `type="array"` properties. See PHPCS 3.3.0 (or my config file) for details. Don't forget to update the comment on line 64.

Similarly, Theme Claim does not yet support this new format, and the RegExp fix may need a bit more thought. I've opened https://github.com/m-e-h/theme-claim/issues/3.

**Comment by samikeijonen** [comment]
@GaryJones I finally got some time to fix these issues!

**Comment by samikeijonen** [comment]
The base work is now in it's own [PHPCS package](https://github.com/samikeijonen/phpcs-composer).
